
name: Workflow1_framework2

on: [push]

jobs:
  test_1:
    runs-on: window-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Maven
      run: mvn clean test --file pom.xml
