
name: Workflow1_framework2

on: [push]

jobs:
  test_1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v
      with:
        java-version: 11
    - name: Test with Maven
      run: mvn clean test --file pom.xml
